### ISSUE TITLE
Deploy API Gateway v1

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ts4nfdi/api-gateway#12]
### TODO

- [ ] Finish and merge the SKOSMOS integration (https://github.com/ts4nfdi/api-gateway/pull/5)
- [ ] Create the first release of API Gateway
- [ ] Deploy to our Kubernetes cluster

**Comment by fillies** [comment]
- [ ] Remove gfbio 
- [ ] Check/test endpoints for autocomplete with roman

**Comment by nichtich** [comment]
Please also add a sentence in README.md about deployment with link to https://github.com/ts4nfdi/api-gateway-deployment
