### ISSUE TITLE
implement the collections prototype 

### ISSUE THREAD

**Issue by syphax-bouazzouni** [ts4nfdi/api-gateway#33]
### TODO

- [ ] Add postgres
- [ ] Add user model and authentication 
- [ ] Add collection model 
- [ ] create crud collection endpoint 
- [ ] Filter search results by a collection 
- [ ] Filter artifacts results by a collection

**Comment by syphax-bouazzouni** [comment]
@Pooya-Oladazimi  @rombaum  @rombaum  to be discuss
